apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: dotnet-backend
  ports:
    - name: backend-port
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
