apiVersion: v1
kind: Secret
metadata:
  name: backend-config-secret
type: Opaque
data:
  AppSettings_Secret: |
    ODkwNWIzNTktM2U5ZS00NGFkLTg0NTYtMzFjYTUwNGY1NTgx
  ConnectionStrings__Minitwit: |
    SG9zdD1kYi1zZXJ2aWNlO0RhdGFiYXNlPU1pbml0d2l0O1VzZXJuYW1lPXNhO1Bhc3N3b3JkPWNi
    MWQzM2M0LWZkYjYtNDM4OS05YTczLWFjZmQ0ZjgzYmY1Mzs=
