apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simulation-ig
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /minitwitsimulation/$1
spec:
  ingressClassName: nginx
  rules:
  - host: eythormikael.com
    http:
      paths:
      - path: /api/(.*)
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ig
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /minitwit/$1
spec:
  ingressClassName: nginx
  rules:
  - host: eythormikael.com
    http:
      paths:
      - path: /backend/(.*)
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ig
spec:
  ingressClassName: nginx
  rules:
  - host: eythormikael.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 3000

