name: apply
on: workflow_dispatch

jobs:
  apply-all:
    name: apply-all-manifests
    runs-on: ubuntu-latest

    steps:
    - name: Set up
      uses: actions/checkout@v3
    # Set up the Kubernetes CLI with your DigitalOcean Kubernetes cluster.
    - name: Set up kubectl
      uses: matootie/dokube@v1.4.0
      with:
        personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
        clusterName: ${{ secrets.CLUSTER_NAME }}

    # Run any kubectl commands you want!
    - name: Run apply script
      run: chmod +x ./apply.sh && ./apply.sh
